return {
  "stevearc/conform.nvim",
  optional = true,
  opts = {
    formatters_by_ft = {
      bash = { "shfmt" },
      sh = { "shfmt" },
      lua = { "stylua" },
      go = { "goimports", "gofumpt", "goimports-reviser" },
      javascript = { { "prettier" } },
      typescript = { { "prettier" } },
      javascriptreact = { { "prettier" } },
      typescriptreact = { { "prettier" } },
      vue = { { "prettier" } },
      css = { { "prettier" } },
      scss = { { "prettier" } },
      less = { { "prettier" } },
      html = { { "prettier" } },
      json = { { "prettier" } },
      jsonc = { { "prettier" } },
      yaml = { { "prettier" } },
      markdown = { { "prettier" } },
      ["markdown.mdx"] = { { "prettier" } },
      graphql = { { "prettier" } },
      handlebars = { { "prettier" } },
      python = { { "ruff", "isort" } },
      rust = { { "rustfmt" } },
    },
  },
}
