# === JetBrains 风格的 typos.toml 配置 ===

[default]
# 核心配置
binary = false
check-filename = true
check-file = true
unicode = true
check-identifiers = true

# 更多IDE特性配置
check-comments = true
check-strings = true
locale = "en-us"

# 忽略特定模式的标识符 - 扩展列表
ignore-identifiers-re = [
  # 基础忽略规则(前面已有)
  
  # 主要Web开发术语
  "api", "apis", "css", "dom", "html", "http", "https", "scss", "svg", "uri", "url", "urls", "ws", "wss", "www", "xhr", "xml",
  
  # 常见数据类型和缩写
  "arr", "bool", "buf", "byte", "char", "dict", "double", "float", "int", "long", "obj", "seq", "short", "str", "struct", "uint", "vec",
  
  # 常见设计模式名称
  "adapter", "builder", "decorator", "factory", "facade", "listener", "mediator", "observer", "proxy", "singleton", "strategy", "visitor",
  
  # 通用前缀/后缀
  "pre.*", "post.*", ".*impl", ".*utils", ".*helper", ".*handler", ".*service", ".*manager", ".*controller", ".*repository", ".*processor",
  
  # 代码常量和枚举风格
  "[A-Z][A-Z0-9_]*",
  
  # React/Vue/Angular组件命名风格
  "[A-Z][a-zA-Z]*Component", "[A-Z][a-zA-Z]*Container", "[A-Z][a-zA-Z]*Provider", "[A-Z][a-zA-Z]*Context",
  
  # 日期时间相关
  "yyyy", "mm", "dd", "hh", "ss", "ms", "ns", "tz", "utc", "iso", "datetime",
  
  # SQL相关
  "jdbc", "sql", "nosql", "ddl", "dml", "schema", "upsert",
  
  # 测试相关
  "mock.*", "stub.*", "fake.*", "test.*", "assert.*", "expect.*", "spec.*", "setup.*", "teardown.*",
  
  # 国际化常用
  "i18n", "l10n", "a11y", "intl", "locale", "locales",
  
  # 算法和数据结构
  "algo", "bfs", "dfs", "dp", "bst", "dag", "trie", "heap", "fifo", "lifo", "lru",
]

# 常见的IDE内置词汇 - 扩展列表
ignore-identifiers = [
  # 基础忽略列表(前面已有)
  
  # 编程概念
  "admin", "alias", "anon", "arg", "args", "async", "auth", "auto", "await", 
  "bg", "blob", "boot", "bot", "build", "cache", "cred", "creds", "crypto", 
  "cwd", "daemon", "debug", "decl", "def", "deps", "dev", "dir", "dirs", "doc",
  "docs", "dsl", "dto", "dylib", "env", "envs", "eval", "exec", "fd", "fg", 
  "fmt", "fn", "fs", "gid", "gz", "impl", "info", "init", "io", "ip", "jit", 
  "kb", "kv", "lang", "langs", "lib", "libs", "log", "logs", "mb", "meta", 
  "mgr", "mod", "mods", "msec", "mutex", "nan", "noop", "ns", "null", "obj", 
  "objs", "op", "ops", "opt", "opts", "os", "param", "params", "perm", "perms",
  "pkg", "pkgs", "proc", "procs", "prog", "proto", "px", "rand", "rc", "recv", 
  "ref", "refs", "regex", "repo", "repos", "req", "reqs", "res", "resp", "ret",
  "rw", "rx", "sem", "serializer", "sig", "stats", "stdin", "stdout", "stderr",
  "subdir", "symlink", "sync", "sys", "tcp", "tls", "tx", "udp", "uid", "ui", 
  "unix", "uri", "url", "urls", "usr", "utf", "uuid", "val", "vals", "vm", 
  "vms", "ws", "yml",
  
  # 常见文件类型
  "avi", "bmp", "csv", "doc", "docx", "eot", "exe", "gif", "ico", "jar", 
  "jpeg", "jpg", "js", "json", "md", "mkv", "mov", "mp3", "mp4", "mpeg", 
  "mpg", "ogg", "pdf", "png", "ppt", "pptx", "rar", "svg", "tar", "tif", 
  "tiff", "toml", "ttf", "txt", "wav", "webm", "webp", "woff", "xls", "xlsx", 
  "xml", "yaml", "yml", "zip",
]

[default.extend-words]
# 前面列表中已有的词汇

# 常见的编程术语
"accessor" = "accessor"
"aiohttp" = "AIOHTTP"
"ajax" = "AJAX"
"alphanumeric" = "alphanumeric"
"ansible" = "Ansible"
"apache" = "Apache"
"appender" = "appender"
"args" = "args"
"ascii" = "ASCII"
"async" = "async"
"auth" = "auth"
"autofill" = "autofill"
"axios" = "Axios"
"backend" = "backend"
"backoff" = "backoff"
"bcrypt" = "bcrypt"
"bitwise" = "bitwise"
"boolean" = "boolean"
"breakpoint" = "breakpoint"
"brotli" = "Brotli"
"bytecode" = "bytecode"
"callback" = "callback"
"camelcase" = "camelCase"
"chai" = "Chai"
"charset" = "charset"
"chmod" = "chmod"
"classpath" = "classpath"
"clickhouse" = "ClickHouse"
"cli" = "CLI"
"codec" = "codec"
"concat" = "concat"
"config" = "config"
"cors" = "CORS"
"couchbase" = "Couchbase"
"cron" = "cron"
"csrf" = "CSRF"
"csv" = "CSV"
"darwin" = "Darwin"
"dataframe" = "DataFrame"
"datetime" = "datetime"
"debian" = "Debian"
"debounce" = "debounce"
"deepcopy" = "deepcopy"
"deps" = "deps"
"dev" = "dev"
"diff" = "diff"
"django" = "Django"
"dockerfile" = "Dockerfile"
"dom" = "DOM"
"dotenv" = "dotenv"
"dsl" = "DSL"
"dto" = "DTO"
"dynamodb" = "DynamoDB"
"elasticsearch" = "Elasticsearch"
"enum" = "enum"
"env" = "env"
"eslint" = "ESLint"
"etcd" = "etcd"
"expr" = "expr"
"fastapi" = "FastAPI"
"favicon" = "favicon"
"fetchall" = "fetchall"
"filepath" = "filepath"
"firefox" = "Firefox"
"flask" = "Flask"
"fmt" = "fmt"
"fn" = "fn"
"foreach" = "foreach"
"formatters" = "formatters"
"frontend" = "frontend"
"fullstack" = "fullstack"
"func" = "func"
"getters" = "getters"
"github" = "GitHub"
"gitlab" = "GitLab"
"golang" = "Golang"
"goroutine" = "goroutine"
"gradle" = "Gradle"
"graphql" = "GraphQL"
"grep" = "grep"
"groovy" = "Groovy"
"gson" = "Gson"
"gzip" = "gzip"
"hashmap" = "HashMap"
"haskell" = "Haskell"
"homebrew" = "Homebrew"
"hostname" = "hostname"
"http" = "HTTP"
"https" = "HTTPS"
"i18n" = "i18n"
"ide" = "IDE"
"idx" = "idx"
"impl" = "impl"
"inet" = "inet"
"influxdb" = "InfluxDB"
"init" = "init"
"inline" = "inline"
"instanceof" = "instanceof"
"io" = "IO"
"ip" = "IP"
"iter" = "iter"
"java" = "Java"
"javascript" = "JavaScript"
"jdbc" = "JDBC"
"jenkins" = "Jenkins"
"jetbrains" = "JetBrains"
"jira" = "Jira"
"jpa" = "JPA"
"jquery" = "jQuery"
"js" = "JS"
"json" = "JSON"
"jsx" = "JSX"
"jwt" = "JWT"
"kotlin" = "Kotlin"
"kubernetes" = "Kubernetes"
"l10n" = "l10n"
"lang" = "lang"
"leveldb" = "LevelDB"
"linq" = "LINQ"
"linux" = "Linux"
"linting" = "linting"
"localhost" = "localhost"
"lodash" = "Lodash"
"macos" = "macOS"
"mapreduce" = "MapReduce"
"matplotlib" = "Matplotlib"
"maven" = "Maven"
"md5" = "MD5"
"memcached" = "Memcached"
"middleware" = "middleware"
"miniapp" = "miniapp"
"minify" = "minify"
"mocha" = "Mocha"
"mongo" = "Mongo"
"mongodb" = "MongoDB"
"monorepo" = "monorepo"
"mqtt" = "MQTT"
"msvc" = "MSVC"
"multipart" = "multipart"
"mutex" = "mutex"
"mysql" = "MySQL"
"namespace" = "namespace"
"nano" = "nano"
"netlify" = "Netlify"
"nginx" = "Nginx"
"node" = "Node"
"nodejs" = "NodeJS"
"noop" = "noop"
"npm" = "npm"
"nullable" = "nullable"
"nullable" = "nullable"
"oauth" = "OAuth"
"obj" = "obj"
"orm" = "ORM"
"param" = "param"
"params" = "params"
"passwd" = "passwd"
"pathname" = "pathname"
"perf" = "perf"
"perl" = "Perl"
"perms" = "perms"
"php" = "PHP"
"pkg" = "pkg"
"postgres" = "Postgres"
"postgresql" = "PostgreSQL"
"pragma" = "pragma"
"prebuilt" = "prebuilt"
"preprocessor" = "preprocessor"
"prettify" = "prettify"
"printf" = "printf"
"proc" = "proc"
"protobuf" = "Protobuf"
"proxied" = "proxied"
"proxies" = "proxies"
"proxy" = "proxy"
"py" = "py"
"pydantic" = "Pydantic"
"pytest" = "Pytest"
"python" = "Python"
"pytorch" = "PyTorch"
"rabbitmq" = "RabbitMQ"
"raspbian" = "Raspbian"
"react" = "React"
"reactjs" = "ReactJS"
"readonly" = "readonly"
"redis" = "Redis"
"redux" = "Redux"
"ref" = "ref"
"regex" = "regex"
"regexp" = "regexp"
"repo" = "repo"
"repos" = "repos"
"req" = "req"
"resolv" = "resolv"
"resp" = "resp"
"restful" = "RESTful"
"rollup" = "Rollup"
"rsync" = "rsync"
"ruby" = "Ruby"
"runtime" = "runtime"
"rust" = "Rust"
"scala" = "Scala"
"scanf" = "scanf"
"scikit" = "Scikit"
"scss" = "SCSS"
"sdk" = "SDK"
"semver" = "SemVer"
"serializable" = "serializable"
"serverless" = "serverless"
"servlet" = "servlet"
"sha" = "SHA"
"shebang" = "shebang"
"sizeof" = "sizeof"
"sklearn" = "sklearn"
"smtp" = "SMTP"
"snackbar" = "snackbar"
"socketio" = "Socket.IO"
"solaris" = "Solaris"
"sprintf" = "sprintf"
"sql" = "SQL"
"sqlite" = "SQLite"
"src" = "src"
"ssh" = "SSH"
"ssl" = "SSL"
"stdlib" = "stdlib"
"stdout" = "stdout"
"str" = "str"
"stringified" = "stringified"
"stringify" = "stringify"
"struct" = "struct"
"stylesheet" = "stylesheet"
"subclass" = "subclass"
"subquery" = "subquery"
"subprocess" = "subprocess"
"subtype" = "subtype"
"sudo" = "sudo"
"supervisord" = "supervisord"
"svelte" = "Svelte"
"svg" = "SVG"
"swiftui" = "SwiftUI"
"symlink" = "symlink"
"sync" = "sync"
"syscall" = "syscall"
"systemd" = "systemd"
"tailwind" = "Tailwind"
"tcp" = "TCP"
"tensorflow" = "TensorFlow"
"ternary" = "ternary"
"testcase" = "testcase"
"threadsafe" = "threadsafe"
"tls" = "TLS"
"tmp" = "tmp"
"tmux" = "tmux"
"todo" = "TODO"
"toml" = "TOML"
"tooltip" = "tooltip"
"travis" = "Travis"
"truthy" = "truthy"
"tsx" = "TSX"
"tuple" = "tuple"
"typescript" = "TypeScript"
"ubuntu" = "Ubuntu"
"udp" = "UDP"
"uint" = "uint"
"uname" = "uname"
"underscore" = "underscore"
"unicode" = "Unicode"
"unix" = "Unix"
"unzip" = "unzip"
"uri" = "URI"
"url" = "URL"
"urls" = "URLs"
"urllib" = "urllib"
"userdata" = "userdata"
"username" = "username"
"utils" = "utils"
"uuid" = "UUID"
"validator" = "validator"
"varchar" = "varchar"
"venv" = "venv"
"vercel" = "Vercel"
"viewport" = "viewport"
"virtualenv" = "virtualenv"
"vscode" = "VSCode"
"vue" = "Vue"
"vuex" = "Vuex"
"webpack" = "Webpack"
"websocket" = "WebSocket"
"whitespace" = "whitespace"
"wsl" = "WSL"
"xamarin" = "Xamarin"
"xcode" = "Xcode"
"xpath" = "XPath"
"xss" = "XSS"
"yaml" = "YAML"
"yml" = "YML"
"zfs" = "ZFS"
"zlib" = "zlib"
"zsh" = "zsh"

# 区分大小写的产品名称
"Github" = "GitHub"
"Gitlab" = "GitLab"
"Javascript" = "JavaScript"
"Typescript" = "TypeScript"
"Postgresql" = "PostgreSQL"
"Mysql" = "MySQL"
"Mongodb" = "MongoDB"
"Nodejs" = "Node.js"
"Redis" = "Redis"
"Npm" = "npm"
"Webpack" = "webpack"
"Vue" = "Vue.js"
"React" = "React"
"Angular" = "Angular"
"Svelte" = "Svelte"
"Django" = "Django"
"Flask" = "Flask"
"Express" = "Express"
"Nestjs" = "NestJS"

# 大小写敏感选项
[default.extend-identifiers]
# 修复常见错误
"environement" = "environment"
"recieve" = "receive"
"occured" = "occurred"
"seperate" = "separate"
"priviledge" = "privilege"
"persistant" = "persistent"
"retreive" = "retrieve"
"paramater" = "parameter"
"dependancy" = "dependency"
"consistant" = "consistent"
"referer" = "referrer"
"teh" = "the"
"implemention" = "implementation"
"definately" = "definitely"
"wierd" = "weird"
"accesible" = "accessible"
"accomodate" = "accommodate"
"acheive" = "achieve"
"acknowlege" = "acknowledge"
"acquaintence" = "acquaintance"
"adquate" = "adequate"
"advertisment" = "advertisement"
"agression" = "aggression"
"alot" = "a lot"
"analysies" = "analyses"
"anual" = "annual"
"apparant" = "apparent"
"arguement" = "argument"
"assesment" = "assessment"
"asyncronous" = "asynchronous"
"availabe" = "available"
"aweful" = "awful"
"beleive" = "believe"
"buisness" = "business"
"calender" = "calendar"
"catagory" = "category"
"cemetary" = "cemetery"
"changable" = "changeable"
"cheif" = "chief"
"collumn" = "column"
"comming" = "coming"
"commited" = "committed"
"comparision" = "comparison"
"compatiblity" = "compatibility"
"compilant" = "compliant"
"concensus" = "consensus"
"concurent" = "concurrent"
"congradulations" = "congratulations"
"consciencious" = "conscientious"
"concious" = "conscious"
"contigous" = "contiguous"
"controll" = "control"
"correspondant" = "correspondent"
"critiscism" = "criticism"
"decieve" = "deceive"
"decendent" = "descendant"
"decription" = "description"
"defendent" = "defendant"
"deffered" = "deferred"
"definate" = "definite"
"definitly" = "definitely"
"deleteing" = "deleting"
"desciption" = "description"
"desireable" = "desirable"
"deterant" = "deterrent"
"developement" = "development"
"didnt" = "didn't"
"disasterous" = "disastrous"
"discription" = "description"
"doesnt" = "doesn't"
"dissapear" = "disappear"
"dissapoint" = "disappoint"
"distributor" = "distributor"
"divison" = "division"
"documention" = "documentation"
"dum" = "dumb"
"efficently" = "efficiently"
"embarass" = "embarrass"
"equiptment" = "equipment"
"esential" = "essential"
"exagerrate" = "exaggerate"
"excede" = "exceed"
"exilerate" = "exhilarate"
"existance" = "existence"
"experiance" = "experience"
"explict" = "explicit"
"expresion" = "expression"
"extention" = "extension"
"factl" = "factual"
"familar" = "familiar"
"finaly" = "finally"
"flourescent" = "fluorescent"
"foriegn" = "foreign"
"foreward" = "forward"
"freind" = "friend"
"fullfil" = "fulfill"
"futher" = "further"
"generaly" = "generally"
"gramar" = "grammar"
"granfather" = "grandfather"
"gaurd" = "guard"
"guidence" = "guidance"
"happend" = "happened"
"harrass" = "harass"
"heighth" = "height"
"heirarchy" = "hierarchy"
"hieght" = "height"
"higeine" = "hygiene"
"hipocrit" = "hypocrite"
"humer" = "humor"
"humerous" = "humorous"
"identiy" = "identity"
"ignorence" = "ignorance"
"imaginery" = "imaginary"
"imediately" = "immediately"
"improvment" = "improvement"
"inadvertant" = "inadvertent"
"incidently" = "incidentally"
"independant" = "independent"
"indispensible" = "indispensable"
"inefficent" = "inefficient"
"interupt" = "interrupt"
"intrisic" = "intrinsic"
"involvment" = "involvement"
"irrelevent" = "irrelevant"
"isnt" = "isn't"
"jist" = "gist"
"knowlege" = "knowledge"
"lenght" = "length"
"liasion" = "liaison"
"libary" = "library"
"likelyhood" = "likelihood"
"likly" = "likely"
"lisence" = "license"
"maintenence" = "maintenance"
"managment" = "management"
"manditory" = "mandatory"
"mathmatics" = "mathematics"
"medcine" = "medicine"
"memeber" = "member"
"milennium" = "millennium"
"miniscule" = "minuscule"
"mispell" = "misspell"
"misterious" = "mysterious"
"modifed" = "modified"
"modulization" = "modularization"
"moent" = "moment"
"momemt" = "moment"
"morgage" = "mortgage"
"mountian" = "mountain"
"mutiply" = "multiply"
"muzzle" = "muzzle"
"neccessary" = "necessary"
"negotation" = "negotiation"
"neighbour" = "neighbor"
"neverthless" = "nevertheless"
"noticable" = "noticeable"
"noticeing" = "noticing"
"obediant" = "obedient"
"occasionaly" = "occasionally"
"occurence" = "occurrence"
"ocurrance" = "occurrence"
"optimisation" = "optimization"
"organise" = "organize"
"orientated" = "oriented"
"outragous" = "outrageous"
"parrallel" = "parallel"
"partialy" = "partially"
"particullarly" = "particularly"
"passanger" = "passenger"
"percieve" = "perceive"
"perfomance" = "performance"
"persistance" = "persistence"
"pertaining" = "pertaining"
"plesant" = "pleasant"
"posession" = "possession"
"possable" = "possible"
"potatos" = "potatoes"
"practise" = "practice"
"preceeding" = "preceding"
"prefered" = "preferred"
"prefrence" = "preference"
"presance" = "presence"
"probaly" = "probably"
"proccess" = "process"
"proffesional" = "professional"
"programable" = "programmable"
"progrom" = "program"
"proove" = "prove"
"propoganda" = "propaganda"
"psoition" = "position"
"ptogress" = "progress"
"puting" = "putting"
"quantiy" = "quantity"
"quarentine" = "quarantine"
"questionaire" = "questionnaire"
"readible" = "readable"
"realy" = "really"
"realiztic" = "realistic"
"reccomend" = "recommend"
"recieve" = "receive"
"reconize" = "recognize"
"refered" = "referred"
"relevent" = "relevant"
"religous" = "religious"
"reluctent" = "reluctant"
"remeber" = "remember"
"repitition" = "repetition"
"reponse" = "response"
"requirment" = "requirement"
"resistence" = "resistance"
"responsability" = "responsibility"
"responsable" = "responsible"
"reutrn" = "return"
"reveiw" = "review"
"rythm" = "rhythm"
"sandwhich" = "sandwich"
"satisifed" = "satisfied"
"schuedule" = "schedule"
"secratary" = "secretary"
"segement" = "segment"
"seige" = "siege"
"sence" = "sense"
"sentance" = "sentence"
"seperat" = "separate"
"sequnce" = "sequence"
"serach" = "search"
"sieze" = "seize"
"significently" = "significantly"
"similer" = "similar"
"simliar" = "similar"
"sincerly" = "sincerely"
"sinse" = "since"
"soley" = "solely"
"speach" = "speech"
"specifc" = "specific"
"specificaly" = "specifically"
"statment" = "statement"
"storey" = "story"
"strat" = "start"
"stricly" = "strictly"
"submittion" = "submission"
"sucessful" = "successful"
"sucess" = "success"
"sufficent" = "sufficient"
"sugest" = "suggest"
"sumary" = "summary"
"supercede" = "supersede"
"supress" = "suppress"
"suprised" = "surprised"
"suprise" = "surprise"
"surity" = "surety"
"surrended" = "surrendered"
"suspention" = "suspension"
"syncronize" = "synchronize"
"syncronized" = "synchronized"
"synchronus" = "synchronous"
"temperture" = "temperature"
"temperarily" = "temporarily"
"tendancy" = "tendency"
"therefor" = "therefore"
"threshhold" = "threshold"
"tommorow" = "tomorrow"
"tommorrow" = "tomorrow"
"tollerance" = "tolerance"
"tomatos" = "tomatoes"
"tragectory" = "trajectory"
"transfered" = "transferred"
"truely" = "truly"
"udpate" = "update"
"unforseen" = "unforeseen"
"unfortunatly" = "unfortunately"
"unknon" = "unknown"
"unliek" = "unlike"
"unecessary" = "unnecessary"
"untill" = "until"
"unuseble" = "unusable"
"useable" = "usable"
"usefull" = "useful"
"utilites" = "utilities"
"utlization" = "utilization"
"vaccum" = "vacuum"
"vegatarian" = "vegetarian"
"vehical" = "vehicle"
"visable" = "visible"
"visibilty" = "visibility"
"volenteer" = "volunteer"
"volounteer" = "volunteer"
"vulnerible" = "vulnerable"
"warrenty" = "warranty"
"wasnt" = "wasn't"
"wensday" = "wednesday"
"whcih" = "which"
"whereever" = "wherever"
"whith" = "with"
"wonderfull" = "wonderful"
"writting" = "writing"
"yeld" = "yield"
"yeild" = "yield"
